# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels: [dependencies, python]
    commit-message:
      prefix: "deps(py)"

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels: [dependencies, javascript]
    commit-message:
      prefix: "deps(npm)"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    labels: [dependencies, github-actions]
    commit-message:
      prefix: "deps(actions)"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    labels: [dependencies, docker]
    commit-message:
      prefix: "deps(docker)"

  - package-ecosystem: docker
    directory: "/frontend"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    labels: [dependencies, docker]
    commit-message:
      prefix: "deps(docker-frontend)"